#version 450
#extension GL_EXT_scalar_block_layout : require

layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer OutData {
    uint things[];
} outData;

layout(set = 0, binding = 1, std430) readonly uniform Values {
    uvec2 v;
} values;

void main() {
    if ((gl_WorkGroupID.x & 1) > 0) {
        outData.things[gl_WorkGroupID.x] = values.v.x;
    } else {
        outData.things[gl_WorkGroupID.x] = values.v.y;
    }
}
