[package]
name = "vk_tracer"
version = "0.1.0"
authors = ["Lucas Malandrino <lucas.malandrino@gmail.com>"]
edition = "2018"

[features]

[dependencies]
thiserror = "^1.0.21"
log = "^0.4.11"

raw-window-handle = "^0.3.3"
ash = "^0.31.0"
ash-window = "^0.5.0"
vk-mem = "^0.2.2"

[dev-dependencies]
winit = "^0.24.0"
anyhow = "1.0.38"
env_logger = "0.8.2"
