name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Build default
      run: cargo build --verbose

  build-no-features:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Build no features
      run: cargo build --no-default-features --verbose

  build-all-features:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Build no features
        run: cargo build --all-features --verbose
